import { useEffect, useMemo, useState } from 'react';
import Panel from '../components/Panel';
import DataTable from '../components/DataTable';
import Icon from '../components/Icon';
import { api, endpoints, unwrap } from '../services/api';
import { DEMO_BOOKINGS, DEMO_MODE } from '../utils/constants';
import { formatDate } from '../utils/formatDate';
function list(p){const v=unwrap(p);return Array.isArray(v)?v:Array.isArray(v?.items)?v.items:[]}
export default function Customers(){const [customers,setCustomers]=useState([]),[query,setQuery]=useState(''),[error,setError]=useState('');useEffect(()=>{(async()=>{try{const p=await api.get(endpoints.bookings.list+'?limit=200');const bookings=list(p);const map=new Map();for(const b of (bookings.length?bookings:DEMO_MODE?DEMO_BOOKINGS:[])){const c=b.customer||{};const name=b.customerName||c.name||b.guestName||'Guest';const phone=b.customerPhone||c.phone||b.phone||'—';const key=c._id||c.id||phone;const prev=map.get(key)||{id:key,name,phone,bookings:0,lastBooking:null,source:new Set()};prev.name=name;prev.phone=phone;prev.bookings+=1;prev.lastBooking=b.bookingDate||b.date||b.createdAt;prev.source.add(b.bookingSource||b.source||'Dashboard');map.set(key,prev)}setCustomers([...map.values()].map(x=>({...x,source:[...x.source].join(', ')})))}catch(e){if(DEMO_MODE)setCustomers(DEMO_BOOKINGS.map((b,i)=>({id:i,name:b.customerName,phone:b.customerPhone,bookings:1,lastBooking:b.bookingDate,source:b.bookingSource})));else setError(e.message)}})()},[]);const rows=useMemo(()=>customers.filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(query.toLowerCase())),[customers,query]);const cols=[{key:'name',label:'Customer',render:r=><><strong>{r.name}</strong><span className="subtext">{r.phone}</span></>},{key:'bookings',label:'Bookings'},{key:'lastBooking',label:'Last booking',render:r=>formatDate(r.lastBooking)},{key:'source',label:'Sources'}];return <div className="page-stack"><div className="page-intro"><div><span className="eyebrow">GUESTS</span><h2>Build a useful guest history.</h2><p>The current backend does not expose a customer route, so this view aggregates customer identities from booking data.</p></div></div><Panel title="Customer directory" subtitle={`${rows.length} guests`} action={<div className="searchbox"><Icon name="search" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search guests"/></div>}>{error&&<div className="alert alert--danger page-alert">{error}</div>}<DataTable columns={cols} rows={rows} empty="No customer history available."/></Panel></div>}
