import { useEffect, useRef, useState } from "react";
import Panel from "../components/Panel";
import DataTable from "../components/DataTable";
import Icon from "../components/Icon";
import { api, endpoints, unwrap } from "../services/api";

const asArray = (payload) => { const value = unwrap(payload); return Array.isArray(value) ? value : Array.isArray(value?.items) ? value.items : []; };
const providerLabel = (name) => ({ twilio: "Twilio", exotel: "Exotel", vobiz: "Vobiz" }[name] || name);

export default function OutboundCalls() {
  const fileRef = useRef(null);
  const [config, setConfig] = useState(null), [phone, setPhone] = useState(""), [provider, setProvider] = useState(""), [message, setMessage] = useState(""), [result, setResult] = useState(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [campaigns, setCampaigns] = useState([]), [campaignName, setCampaignName] = useState("Guest follow-up"), [file, setFile] = useState(null), [campaignProvider, setCampaignProvider] = useState(""), [concurrency, setConcurrency] = useState(2), [messageTemplate, setMessageTemplate] = useState("Hello {name}, this is a follow-up from our restaurant."), [preview, setPreview] = useState(null), [campaignBusy, setCampaignBusy] = useState(false);
  const load = async () => { try { const [cfg, cams] = await Promise.all([api.get(endpoints.outbound.config), api.get(`${endpoints.outbound.campaigns}?limit=50`)]); const c = unwrap(cfg); setConfig(c); const active = c?.activeProvider || "twilio"; setProvider((current) => current || active); setCampaignProvider((current) => current || active); setCampaigns(asArray(cams)); } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (config?.activeProvider) { setProvider((current) => current || config.activeProvider); setCampaignProvider((current) => current || config.activeProvider); } }, [config]);
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(""); setResult(null); try { setResult(await api.post(endpoints.outbound.call, { phoneNumber: phone, provider, message })); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const previewFile = async () => { if (!file) return; setCampaignBusy(true); setError(""); try { const fd = new FormData(); fd.append("file", file); const response = await api.post(endpoints.outbound.campaignPreview, fd); setPreview(unwrap(response)); } catch (e) { setError(e.message); } finally { setCampaignBusy(false); } };
  const createCampaign = async (e) => { e.preventDefault(); if (!file) return setError("Choose a CSV, XLSX or XLSM file first."); setCampaignBusy(true); setError(""); try { const fd = new FormData(); fd.append("file", file); fd.append("name", campaignName); fd.append("provider", campaignProvider); fd.append("concurrency", String(concurrency)); fd.append("messageTemplate", messageTemplate); await api.post(endpoints.outbound.campaigns, fd); setPreview(null); setFile(null); if (fileRef.current) fileRef.current.value = ""; await load(); setResult({ success: true, message: "Campaign created. Start it from the campaign table." }); } catch (e) { setError(e.message); } finally { setCampaignBusy(false); } };
  const start = async (id) => { try { await api.post(endpoints.outbound.campaignStart(id)); await load(); } catch (e) { setError(e.message); } };
  const stop = async (id) => { try { await api.post(endpoints.outbound.campaignCancel(id)); await load(); } catch (e) { setError(e.message); } };
  const campaignColumns = [{key:"name",label:"Campaign"},{key:"provider",label:"Provider",render:r=>providerLabel(r.provider)},{key:"status",label:"Status"},{key:"total",label:"Contacts"},{key:"successCount",label:"Successful"},{key:"failedCount",label:"Failed"},{key:"createdAt",label:"Created",render:r=>new Date(r.createdAt).toLocaleString()},{key:"actions",label:"Actions",render:r=><div className="row-actions"><button className="table-action" type="button" disabled={r.status === "running" || r.status === "completed" || r.status === "cancelled"} onClick={(e)=>{e.stopPropagation();start(r._id)}}>Start</button><button className="table-action table-action--danger" type="button" disabled={r.status === "completed" || r.status === "cancelled"} onClick={(e)=>{e.stopPropagation();stop(r._id)}}>Stop</button></div>}];
  return <div className="page-stack">
    <div className="page-intro"><div><span className="eyebrow">OUTBOUND</span><h2>Single calls and bulk campaigns.</h2><p>Switch between configured telephony providers from Settings, or override the provider for one outbound call.</p></div><button className="secondary-button" type="button" onClick={load}><Icon name="refresh" size={16}/>Refresh</button></div>
    {error && <div className="alert alert--danger">{error}</div>}
    <Panel title="Provider readiness" subtitle={`Global active provider: ${providerLabel(config?.activeProvider || "—")}`}><div className="stack-status">{["twilio","exotel","vobiz"].map((name)=><div key={name}><span>{providerLabel(name)}</span><strong>{config?.providers?.[name] ? "Configured" : "Not configured"}</strong></div>)}</div></Panel>
    <div className="dashboard-grid">
      <Panel title="Single outbound call" subtitle="Credentials stay on the server"><form className="form-stack" onSubmit={submit}><label>Provider<select value={provider} onChange={(e)=>setProvider(e.target.value)}>{["twilio","exotel","vobiz"].map((x)=><option key={x} value={x}>{providerLabel(x)}</option>)}</select></label><label>Guest phone<input required value={phone} onChange={(e)=>setPhone(e.target.value)} placeholder="+91 98765 43210"/></label><label>Message<textarea rows="5" value={message} onChange={(e)=>setMessage(e.target.value)} placeholder="Follow up about a reservation."/></label><button className="primary-button" disabled={busy} type="submit"><Icon name="phone-out" size={16}/>{busy?"Starting…":"Start call"}</button></form>{result&&<pre className="json-preview">{JSON.stringify(result,null,2)}</pre>}</Panel>
      <Panel title="Bulk outbound" subtitle="CSV / Excel import → preview → campaign"><form className="form-stack" onSubmit={createCampaign}><label>Campaign name<input required value={campaignName} onChange={(e)=>setCampaignName(e.target.value)}/></label><label>Provider<select value={campaignProvider} onChange={(e)=>setCampaignProvider(e.target.value)}>{["twilio","exotel","vobiz"].map((x)=><option key={x} value={x}>{providerLabel(x)}</option>)}</select></label><label>Concurrent calls<input type="number" min="1" max="10" value={concurrency} onChange={(e)=>setConcurrency(e.target.value)}/></label><label>Message template<textarea rows="4" value={messageTemplate} onChange={(e)=>setMessageTemplate(e.target.value)}/></label><label>Contact file<input ref={fileRef} required type="file" accept=".csv,.xlsx,.xlsm" onChange={(e)=>setFile(e.target.files?.[0]||null)}/></label><div className="helper-text">Required: phone/mobile/number. Optional: name, email, message/notes. Use <code>{`{name}`}</code> in the template.</div><div className="row-actions"><button className="secondary-button" type="button" disabled={!file||campaignBusy} onClick={previewFile}>Preview</button><button className="primary-button" disabled={!file||campaignBusy} type="submit">{campaignBusy?"Working…":"Create campaign"}</button></div></form>{preview&&<div className="preview-box"><strong>{preview.total} valid contacts</strong><DataTable columns={[{key:"rowNumber",label:"Row"},{key:"name",label:"Name"},{key:"phone",label:"Phone"},{key:"email",label:"Email"}]} rows={preview.preview||preview.contacts||[]} empty="No valid contacts."/></div>}</Panel>
    </div>
    <Panel title="Campaigns" subtitle="Durable status and per-contact call state"><DataTable columns={campaignColumns} rows={campaigns} empty="No campaigns yet."/></Panel>
  </div>;
}
